import { gql, useQuery } from "@apollo/client";
import Head from "next/head";
import { addApolloState, initializeApollo } from "../lib/apolloClient";
import styles from "../styles/Home.module.css";

const QUERY = gql`
  query allProducts {
    products {
      id
      slug
      image {
        id
        formats
      }
      title
      description
    }
  }
`;

function HomePage() {
  const { data } = useQuery<{ products: any[] }>(QUERY);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {JSON.stringify(data.products)}
    </div>
  );
}

export async function getStaticProps() {
  const apolloClient = initializeApollo();

  await apolloClient.query({
    query: QUERY,
  });

  return addApolloState(apolloClient, {
    props: {},
    revalidate: 1,
  });
}

export default HomePage;
